server:
  rootPath: /api/
  applicationConnectors:
    - type: http
      port: 3001
  adminConnectors:
    - type: http
      port: 3002
databaseResource:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: 786Hh@786
  url: jdbc:mysql://localhost:3306/dropTest
  properties:
    hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.show_sql: true
    charSet: UTF-8
  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 5s
  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"
  # the minimum number of connections to keep open
  minSize: 8
  # the maximum number of connections to keep open
  maxSize: 32


swagger:
  resourcePackage: com.technohack.resources
  title: User API
  description: CRUD operations for User entity
  contact: harshchaurasiya6768@gmail.com
  license: Apache 2.0
  version: 1.0.0