server:
  rootPath: /api/
  applicationConnectors:
    - type: http
      port: 3001
  adminConnectors:
    - type: http
      port: 3002
databaseResource:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: 786Hh@786
  url: jdbc:mysql://localhost:3306/dropTest
  properties:
    hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.show_sql: true
    charSet: UTF-8